server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oneblog?characterEncoding=utf-8
    druid:
      username: root
      password: Kingback666
      driver-class-name: com.mysql.jdbc.Driver
  web:
    resources:
      static-locations: classpath:static/,file:static/

